### ISSUE TITLE
TypeError when extracting Named Trails

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/OpenTrails#66] opened 2014-07-12 14:09 UTC
Bug encountered when attempting to convert [segment data from Santa Clara county](https://github.com/codeforamerica/PLATS/blob/5a8ae5a961eb5c77807e0b9879c2214552bb9b24/test-files/santa-clara-segments.zip) locally.

Will try to reproduce on the production app so I can provide a URL. Here is a screenshot for the time being.

![screenshot 2014-07-12 17 06 30](https://cloud.githubusercontent.com/assets/2983464/3561614/eba07564-09cd-11e4-97d8-d8450a9fa704.png)

**Comment by migurski** [comment] 2014-07-12 15:28
I can't reproduce this in either the production app or my local copy.

**Comment by alanjosephwilliams** [comment] 2014-07-14 16:31
I'm still seeing this error, both locally and in production, with the sample data referenced.

On production, we generate an HTML-only page that says simply "Internal Server Error". The heroku logs match the flask debugger. After I finish content-v3, I'll take a look at debugging.

**Comment by migurski** [comment] 2014-07-14 16:47
Excellent. I plan to add this data to the tests.

**Comment by migurski** [comment] 2014-08-11 00:10
Fixed in 17bcc8c.

**Closed as completed** 2014-08-11 00:11 UTC
Labels: bug
